### ISSUE TITLE
Action fails with missing repository error

### ISSUE THREAD

**Issue by fmigneault** [max/secret-scan#1]
Using below configuration: 
```
name: Secret Scan
on:
  - pull_request
  - push
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: max/secret-scan@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

I get the follow error:
```
Traceback (most recent call last):
  File "/usr/local/bin/trufflehog", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 82, in main
    surpress_output=False, branch=args.branch, repo_path=args.repo_path, path_inclusions=path_inclusions, path_exclusions=path_exclusions)
  File "/usr/local/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 309, in find_strings
    project_path = clone_git_repo(git_url)
  File "/usr/local/lib/python2.7/site-packages/truffleHog/truffleHog.py", line 152, in clone_git_repo
    Repo.clone_from(git_url, project_path)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 925, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/repo/base.py", line 880, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python2.7/site-packages/git/util.py", line 341, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v /github/workspace /tmp/tmphhgegP
  stderr: 'fatal: repository '/github/workspace' does not exist
'
```

Volumes are mounted during `docker run` call.
(`-v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"`).
Not too sure why this is failing here.

**Comment by vikramnr** [comment]
Attaching Log file
[log.txt](https://github.com/max/secret-scan/files/3955784/log.txt)
